### PR TITLE
Tidy up Mu, termination process and keep alive

### LINKED ISSUE #227: Autopaho set DefaultPinger on ClientConfig can't reconnect to server after disconnection
**Describe the bug**
Autopaho set DefaultPinger on ClientConfig can't reconnect to the server after disconnection
Found this bug while using DefalutPinger with logger to test Pinger with autopaho (I guess this is only usecase for now)

**To reproduce**
1. Set PingHandler to DefaultPinger on ClientConfig and autopaho.NewConnection
```go
pinger := paho.NewDefaultPinger()
cfg := autopaho.ClientConfig{
    ...
    ClientConfig: paho.ClientConfig{
        ....
        PingHandler: pinger,
        ....
    }
    ...
}
cm, err := autopaho.NewConnection(ctx, cfg)
```
2. Disconnect client network and wait for client being closed
3. Reconnect network -> But autopaho can't reconnect to the server

**Debug output**
```
2024/01/13 10:00:54 connecting
2024/01/13 10:00:54 sending CONNECT
2024/01/13 10:00:54 waiting for CONNACK/AUTH
2024/01/13 10:00:55 received CONNACK
mqtt connection up
client error: ping handler error: Run() already called
2024/01/13 10:00:55 received CONNACK, starting PingHandler
2024/01/13 10:00:55 starting publish packets loop
2024/01/13 10:00:55 starting incoming
2024/01/13 10:00:55 subscribing to …
2024/01/13 10:00:55 PacketSent() returning due to done channel
2024/01/13 10:00:55 waiting for SUBACK
2024/01/13 10:00:55 returning from ping handler worker
2024/01/13 10:00:55 error called: ping handler error: Run() already called
2024/01/13 10:00:55 client stopped
2024/01/13 10:00:55 stop() called with error: <nil>
2024/01/13 10:00:55 ping stopped
2024/01/13 10:00:55 conn closed
2024/01/13 10:00:55 acks tracker reset
2024/01/13 10:00:55 session updated, waiting on workers
2024/01/13 10:00:55 client stopping, incoming stopping
2024/01/13 10:00:55 returning from incoming worker
2024/01/13 10:00:55 queue got connection
2024/01/13 10:00:55 returning from publish packets loop worker
2024/01/13 10:00:55 workers done
2024/01/13 10:00:55 handleError received error: ping handler error: Run() already called
2024/01/13 10:00:55 handleError passed error on: ping handler error: Run() already called
```

**Expected behaviour**
autopaho should be able to reconnect to the server even previous client was closed.

**Software used:**
- Client version: e379c50417faa1e52adef46ea24f25737a0df707

**Additional context**
It happens because the values of Pinger in paho.ClientConfig is changed and autopaho uses this changed values to reconnect to the server
```go
func (p *DefaultPinger) Run(conn net.Conn, keepAlive uint16) error {
	if keepAlive == 0 {
		p.debug.Println("Run() returning immediately due to keepAlive == 0")
		return nil
	}
	if conn == nil {
		return fmt.Errorf("conn is nil")
	}
	p.mu.Lock()
	if p.timer != nil {
		p.mu.Unlock()
		return fmt.Errorf("Run() already called")
	}
	select {
	case <-p.done:
		p.mu.Unlock()
		return fmt.Errorf("Run() called after stop()")
	default:
	}
	p.keepAlive = keepAlive
	p.conn = conn
	p.timer = time.AfterFunc(0, p.sendPingreq) // Immediately send first pingreq
	p.mu.Unlock()

	return <-p.errChan
}
```
timer is set while Run()
so the timer of the Pinger in paho.ClientConfig is not nil after that, and it causes `return fmt.Errorf("Run() already called")` while trying reconnection
It's not only problem of timer, but done(+ other channels I guess?) and stopOnce should also be initialized in order to work correctly

This is not a critical bug because users don't need logger for production, but it would be good to fix I guess.

### PR DESCRIPTION
**Pull request by MattBrittan**
* It was unclear what Client.mu protected.
* Using and using contexts to manage shutdown is easier to follow. 
* Reimplement Pinger using Context

Closes #227
Ref #148

### CODE REVIEW

File: paho/pinger.go [hunk 1]
```diff
@@ -81,106 +73,67 @@ func (p *DefaultPinger) Run(conn net.Conn, keepAlive uint16) error {
...
-		return fmt.Errorf("Run() already called")
+		return fmt.Errorf("Run() already in progress")
 	}
-	select {
-	case <-p.done:
+	p.running = true
+	p.mu.Unlock()
+	defer func() {
+		p.mu.Lock()
 		p.mu.Unlock()
```
Comment (Widgle) [inline paho/pinger.go:84]: Guess defer is missing?

File: paho/pinger.go [hunk 2]
```diff
@@ -81,106 +73,67 @@ func (p *DefaultPinger) Run(conn net.Conn, keepAlive uint16) error {
...
+			p.mu.Unlock()
+
+			if !lastPingSent.IsZero() && lastPingSent.After(lastPingResponse) {
+				p.debug.Printf("DefaultPinger PINGRESP timeout")
+				return fmt.Errorf("PINGRESP timed out")
+			}
+
+			if t.Before(pingDue) {
+				// A Control Packet has been sent since we last checked, meaning the ping can be delayed
+				timer.Reset(t.Sub(pingDue))
```
Comment (Widgle) [inline paho/pinger.go:109]: Supposed to be pingDue.Sub(t)?

File: paho/client.go [hunk 3]
```diff
@@ -224,17 +227,29 @@ func (c *Client) Connect(ctx context.Context, cp *Connect) (*Connack, error) {
...
+	// Connect twice is invalid.
+	c.connectCalledMu.Lock()
+	if c.connectCalled {
+		c.connectCalledMu.Unlock()
+		return nil, fmt.Errorf("connect must only be called once")
+	}
+	c.connectCalled = true
+	c.connectCalledMu.Unlock()
+
+	// The passed in ctx applies to the connection process only. clientCtx applies to Client (signals
```
Comment (vishnureddy17) [inline paho/client.go:241]: Looks like you meant to say more here in this comment

File: paho/pinger.go (hunk 2 above)
Comment (MattBrittan) [reply paho/pinger.go]: OOps, corrected this

Comment (MattBrittan) [reply paho/pinger.go]: Thanks, have moved the Unlock to the end.

File: paho/pinger.go (hunk 1 above)
Comment (MattBrittan) [reply paho/pinger.go]: Thanks, have moved the Unlock to the end.

File: paho/client.go [hunk 4]
```diff
@@ -72,9 +72,8 @@ type (
 		Session          session.SessionManager
 		autoCloseSession bool
 
-		AuthHandler   Auther
-		PingHandler   Pinger
-		defaultPinger bool
```
Comment (vishnureddy17) [inline paho/client.go:77]: This should be kept and its value should be used to determine whether `SetDebugLogger` should call `SetDebug` on the `Pinger`.

File: paho/client.go (hunk 3 above)
Comment (MattBrittan) [reply paho/client.go]: Thanks - completed this

File: paho/client.go (hunk 4 above)
Comment (MattBrittan) [reply paho/client.go]: Thanks - I guessed it was there for something like that. Added code to set the logger.

**Comment by izarraga** [comment]
This bug has also happened to me.  When you commit PR#229 i will check again.

File: paho/pinger.go [hunk 5]
```diff
@@ -81,106 +73,67 @@ func (p *DefaultPinger) Run(conn net.Conn, keepAlive uint16) error {
...
+				return fmt.Errorf("PINGRESP timed out")
+			}
+
+			if t.Before(pingDue) {
+				// A Control Packet has been sent since we last checked, meaning the ping can be delayed
+				timer.Reset(pingDue.Sub(t))
+				continue
+			}
+
+			if _, err := packets.NewControlPacket(packets.PINGREQ).WriteTo(conn); err != nil {
```
Comment (Lorderot) [inline paho/pinger.go:113]: can this potentially block for a very long time, breaking the keep alive mechanism?

File: paho/pinger.go [hunk 6]
```diff
@@ -81,106 +73,67 @@ func (p *DefaultPinger) Run(conn net.Conn, keepAlive uint16) error {
...
+	var lastPingSent time.Time
+	for {
+		select {
+		case <-ctx.Done():
+			timer.Stop() // We don't care if the timer has fired
+			return nil
+		case t := <-timer.C:
+			p.mu.Lock()
+			lastPingResponse := p.lastPingResponse
+			pingDue := p.lastPacketSent.Add(interval)
```
Comment (Lorderot) [inline paho/pinger.go:99]: "packet is sent" isn't equal to "packet is received". Are we sure that it always guarantees that the connection is not broken? Do we always receive something from the cloud in response (e.g. publishes with QoS 0)? Looks like it can significantly postpone the closure of connection in some edge cases.

Comment (MattBrittan) [reply paho/pinger.go:99]: This is as per MQTT-3.1.2-20 (the only requirement to send a keep alive is if no control packet has been sent within the time frame). If you have a really broken TCP connection (that is something is ACKing packets that have not actually been delivered) then this could be an issue (but the MQTT protocol relies on a standards compliant connection).

File: paho/pinger.go (hunk 5 above)
Comment (Lorderot) [reply paho/pinger.go:113]: If the connection is mostly idle, we rely on keepalives to detect network issues. PingHandler sends a PINGREQ, and if it doesn't receive a response within KeepAlive period, the client will be closed. However, this logic breaks in the edge cases when PingHandler hangs on the WriteTo(conn) operation due to some network issues; the call will be eventually unblocked due to the TCP timeout, but it could be way longer than the specified KeppAlive period. 

Isn't it better to send a packet in a separate goroutine; and in case a response is not received within the KeepAlive period, close the connection (which would unblock the potentially stuck goroutine)?

Comment (MattBrittan) [reply paho/pinger.go:113]: >Isn't it better to send a packet in a separate goroutine

OK - when you said it could block I thought you meant it was blocked because a message was being transmitted. This can happen, if you send a large message over a slow link there is a potential for it to take longer than  `keepAlive` to be transmitted (and there is not much we can do about that).

I believe the defaults for TCP retransmission periods are something like 13 to 30 minutes on Linux and around 65 seconds on windows. so there does appear to be a potential for the  `Write` to block longer than the keepalive period.

So there may be a rationale for moving the `Send` to a goroutine but I think that should be a separate issue/PR (this PR was more about tidying things up and removing a potential deadlock so the way the packet is sent was not changed from previous code).

I would note that the much older `paho.mqtt.golang` sends pings in the same way (does not include any checks re how long the send takes) and I don't believe any issues have been raised.

Comment (Lorderot) [reply paho/pinger.go:113]: Created a [PR](https://github.com/eclipse/paho.golang/pull/257).
